In [ ]:
import sqlite3
import pandas as pd

connection = sqlite3.connect('database.db')
# cursor = connection.cursor()
print(connection)

In [ ]:
sql_query = """
create table customers (
    email text primary key,
    name text not null,
    phone numeric unique
);
"""
cursor = connection.cursor()
cursor.execute(sql_query)
connection.commit()
print("Table created successfully")


In [ ]:
sql_query = """
insert into customers (
    email,
    name,
    phone
) values (
    'phudht@gmail.com',
    'Do Phu',
    1234567890
);
"""
cursor = connection.cursor()
cursor.execute(sql_query)
connection.commit()
print("Table inserted successfully")


In [ ]:
data = pd.read_sql_query("SELECT * FROM customers;", connection)
print(data)

In [ ]:
values = [
    ('phu1@gmail.com', 'Phu One', 1111111111),
    ('phu2@gmail.com', 'Phu Two', 2222222222),
    ('phu3@gmail.com', 'Phu Three', 3333333333)
]

sql_query = """
insert into customers (email, name, phone) values (?, ?, ?);
"""

cursor = connection.cursor()
cursor.executemany(sql_query, values)
connection.commit()
print("Multiple records inserted successfully")

data = pd.read_sql_query("SELECT * FROM customers;", connection)
print(data)

In [15]:
sql_query = """
update customers
set phone = 9999999999
where email = 'phu1@gmail.com'
;
"""
cursor = connection.cursor()
cursor.execute(sql_query)
connection.commit()
print("Record updated successfully")

Record updated successfully


In [16]:
sql_query = """
delete from customers
where email = 'phu1@gmail.com'
;
"""
cursor = connection.cursor()
cursor.execute(sql_query)
connection.commit()
print("Record deleted successfully")

data = pd.read_sql_query("SELECT * FROM customers;", connection)
print(data)

Record deleted successfully
              email       name       phone
0  phudht@gmail.com     Do Phu  1234567890
1    phu2@gmail.com    Phu Two  2222222222
2    phu3@gmail.com  Phu Three  3333333333


In [ ]:
sql_query = """
delete from customers
where email = 'phu2@gmail.com'
;
"""
cursor = connection.cursor()
cursor.execute(sql_query)
connection.commit()
print("Record deleted successfully")

data = pd.read_sql_query("SELECT * FROM customers;", connection)
print(data)

# Mattrix

In [30]:
import random
import numpy as np

arr = np.random.randint(1, 101, size=(3, 5))
print(arr)
matrix = arr.tolist()

print("\nSố lớn nhất trên mỗi hàng:")
# for i, row in enumerate(matrix):
#     print(f"Dòng {i + 1}: {max(row)}")

for i in arr:
    result = np.max(i)
    print(f"Dòng {i}: {result}")

new_arr = arr.T
print("\nSố lớn nhất của mỗi cột:")
# for col in range(5):
#     max_col = max(matrix[row][col] for row in range(3))
#     print(f"Cột {col + 1}: {max_col}")

for i in new_arr:
    result = np.max(i)
    print(f"Cột {i}: {result}")

[[43 37 69 22 16]
 [83 67 90 48 72]
 [44 25 27 54 95]]

Số lớn nhất trên mỗi hàng:
Dòng [43 37 69 22 16]: 69
Dòng [83 67 90 48 72]: 90
Dòng [44 25 27 54 95]: 95

Số lớn nhất của mỗi cột:
Cột [43 83 44]: 83
Cột [37 67 25]: 67
Cột [69 90 27]: 90
Cột [22 48 54]: 54
Cột [16 72 95]: 95


In [ ]:
from flask import Flask

app = Flask(__name__)
@app.route('/')
def Hello():
    return "Hello, Flask!"
if __name__ == '__main__':
    app.run(debug=True)